Tue, 20 Aug 2019 11:35:59 log.py[line:17] DEBUG 读取配置项发生了错误,zone,门诊患者中药饮片总费用
Tue, 20 Aug 2019 11:35:59 log.py[line:20] ERROR No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x82\xa3\xe8\x80\x85\xe4\xb8\xad\xe8\x8d\xaf\xe9\xa5\xae\xe7\x89\x87\xe6\x80\xbb\xe8\xb4\xb9\xe7\x94\xa8' in section: 'zone'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 27, in get
    return self.conf.get(field,key)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option '\xe9\x97\xa8\xe8\xaf\x8a\xe6\x82\xa3\xe8\x80\x85\xe4\xb8\xad\xe8\x8d\xaf\xe9\xa5\xae\xe7\x89\x87\xe6\x80\xbb\xe8\xb4\xb9\xe7\x94\xa8' in section: 'zone'
Tue, 20 Aug 2019 11:44:55 log.py[line:17] DEBUG 读取配置项发生了错误,zone,出院患者使用中药饮片总金额
Tue, 20 Aug 2019 11:44:55 log.py[line:20] ERROR No option '\xe5\x87\xba\xe9\x99\xa2\xe6\x82\xa3\xe8\x80\x85\xe4\xbd\xbf\xe7\x94\xa8\xe4\xb8\xad\xe8\x8d\xaf\xe9\xa5\xae\xe7\x89\x87\xe6\x80\xbb\xe9\x87\x91\xe9\xa2\x9d' in section: 'zone'
Traceback (most recent call last):
  File "C:\Users\ipharmacare\newreport\common\configReader.py", line 27, in get
    return self.conf.get(field,key)
  File "C:\Users\ipharmacare\python27\lib\ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option '\xe5\x87\xba\xe9\x99\xa2\xe6\x82\xa3\xe8\x80\x85\xe4\xbd\xbf\xe7\x94\xa8\xe4\xb8\xad\xe8\x8d\xaf\xe9\xa5\xae\xe7\x89\x87\xe6\x80\xbb\xe9\x87\x91\xe9\xa2\x9d' in section: 'zone'
